In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.

print(np.__version__)

1.17.2


In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))

In [4]:
#4. Print a.
print(a)

[[[0.18012191 0.59928234 0.0488124  0.46786227 0.93262131]
  [0.67239849 0.11200714 0.6847132  0.24576023 0.26137089]
  [0.18996794 0.75186829 0.03170896 0.9829499  0.80765932]]

 [[0.81765228 0.00671671 0.69077067 0.26272766 0.30542187]
  [0.87208946 0.90812417 0.65878775 0.98750215 0.60448808]
  [0.70526565 0.85672318 0.86177041 0.56463398 0.69978604]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.ones((5,2,3))

In [6]:
#6. Print b.
print('Exercise 6')
print(b)

Exercise 6
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [7]:
#7. Do a and b have the same size? How do you prove that in Python code?
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)
# They have different size. Not possible in python to multiply two arrays with different size

In [8]:
#8. Are you able to add a and b? Why or why not?

#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

In [9]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
print('Exercise 9')
c = b.reshape(2,3,5)
print(c.shape, c)

Exercise 9
(2, 3, 5) [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [10]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
print('Exercise 10')
d= (a+c)
# it works because a and c have the same size

Exercise 10


In [27]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("Exercise 11")
print(a)
print("And d")
print(d)
#d array is the same as a but every element has a +1 value.

Exercise 11
[[1.81765228 1.00671671 1.69077067 1.26272766 1.30542187]
 [1.87208946 1.90812417 1.65878775 1.98750215 1.60448808]
 [1.70526565 1.85672318 1.86177041 1.56463398 1.69978604]]
And d
[[[1.18012191 1.59928234 1.0488124  1.46786227 1.93262131]
  [1.67239849 1.11200714 1.6847132  1.24576023 1.26137089]
  [1.18996794 1.75186829 1.03170896 1.9829499  1.80765932]]

 [[1.81765228 1.00671671 1.69077067 1.26272766 1.30542187]
  [1.87208946 1.90812417 1.65878775 1.98750215 1.60448808]
  [1.70526565 1.85672318 1.86177041 1.56463398 1.69978604]]]
2


In [12]:
#12. Multiply a and c. Assign the result to e.
print('Exercise 12')
e = a*c

Exercise 12


In [13]:
#13. Does e equal to a? Why or why not?
print('Exercise 13')
print(e == a)
# All the elements are equal so both arrays are equal

Exercise 13
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [14]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
print('Exercise 14')
d_max=np.max(d)
print(f'd_max: {d_max}')
d_min=np.min(d)
print(f'd_min: {d_min}')
d_mean=np.mean(d)
print(f'd_mean: {d_mean}')

Exercise 14
d_max: 1.9875021463217186
d_min: 1.0067167092572773
d_mean: 1.5590521544105307


In [37]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
print('Exercise 15')
f = np.empty([2,3,5])
print(f)

Exercise 15
[[[1.18012191 1.59928234 1.0488124  1.46786227 1.93262131]
  [1.67239849 1.11200714 1.6847132  1.24576023 1.26137089]
  [1.18996794 1.75186829 1.03170896 1.9829499  1.80765932]]

 [[1.81765228 1.00671671 1.69077067 1.26272766 1.30542187]
  [1.87208946 1.90812417 1.65878775 1.98750215 1.60448808]
  [1.70526565 1.85672318 1.86177041 1.56463398 1.69978604]]]


In [38]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
print('Exercise 16')
list_middle=[]                        # create an empty list to append all the results of the "unpacking"
for a in f:
    for b in a:
        for c in b:             #unpacking all the 3D array
            if (d_min < c < d_mean):
               list_middle.append(25)
            elif (d_mean < c < d_max):
               list_middle.append(75)
            elif c == d_mean:
               list_middle.append(50)
            elif c == d_min:
               list_middle.append(0)
            elif c == d_max:
               list_middle.append(100)
         
f = np.reshape(list_middle, (2,3,5))
print(f)

Exercise 16
[[[1.18012191 1.59928234 1.0488124  1.46786227 1.93262131]
  [1.67239849 1.11200714 1.6847132  1.24576023 1.26137089]
  [1.18996794 1.75186829 1.03170896 1.9829499  1.80765932]]

 [[1.81765228 1.00671671 1.69077067 1.26272766 1.30542187]
  [1.87208946 1.90812417 1.65878775 1.98750215 1.60448808]
  [1.70526565 1.85672318 1.86177041 1.56463398 1.69978604]]]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [ ]:
#not quite the same solution as expected because I did not append the results into f but instead create a new list

#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to 
        [ 'B',  'D',   'A',  'D', 'D']]])use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],
       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
Again, you don't need Numpy in this question.

In [42]:
list_middle=[]                        # create an empty list to append all the results of the "unpacking"
for a in f:
    for b in a:
        for c in b:             #unpacking all the 3D array
            if (d_min < c < d_mean):
               list_middle.append('B')
            elif (d_mean < c < d_max):
               list_middle.append('D')
            elif c == d_mean:
               list_middle.append('C')
            elif c == d_min:
               list_middle.append('A')
            elif c == d_max:
               list_middle.append('D')
         
f = np.reshape(list_middle, (2,3,5))
print(f)

[[['B' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'D']]

 [['D' 'A' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'D' 'D']]]
