In [8]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [9]:
#2. Print the NUMPY version and the configuration.

print(np.__version__)

1.17.2


In [10]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a=np.random.random((2,3,5))

In [11]:
#4. Print a.
print(a)

[[[0.23329397 0.9768525  0.10099104 0.3698607  0.41405295]
  [0.88659816 0.46745248 0.27761463 0.84530968 0.32235025]
  [0.3369242  0.24311748 0.7637154  0.11012322 0.74792939]]

 [[0.19979279 0.38372494 0.45644645 0.50340292 0.20487276]
  [0.95592744 0.34301452 0.47063378 0.1874014  0.82330324]
  [0.86503144 0.36822569 0.33413658 0.60327999 0.900709  ]]]


In [12]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b= np.ones((5,2,3))

In [13]:
#6. Print b.
print('Exercise 6')
print(b)

Exercise 6
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [14]:
#7. Do a and b have the same size? How do you prove that in Python code?
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)
# They have different size. Not possible in python to multiply two arrays with different size

In [15]:
#8. Are you able to add a and b? Why or why not?

#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3)

In [16]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
print('Exercise 9')
c = b.reshape(2,3,5)
print(c.shape, c)

Exercise 9
(2, 3, 5) [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [17]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
print('Exercise 10')
d= (a+c)
# it works because a and c have the same size

Exercise 10


In [18]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("Exercise 11")
print(a)
print(d)

#d array is the same as a but every element has a +1 value.

Exercise 11
[[[0.23329397 0.9768525  0.10099104 0.3698607  0.41405295]
  [0.88659816 0.46745248 0.27761463 0.84530968 0.32235025]
  [0.3369242  0.24311748 0.7637154  0.11012322 0.74792939]]

 [[0.19979279 0.38372494 0.45644645 0.50340292 0.20487276]
  [0.95592744 0.34301452 0.47063378 0.1874014  0.82330324]
  [0.86503144 0.36822569 0.33413658 0.60327999 0.900709  ]]]
[[[1.23329397 1.9768525  1.10099104 1.3698607  1.41405295]
  [1.88659816 1.46745248 1.27761463 1.84530968 1.32235025]
  [1.3369242  1.24311748 1.7637154  1.11012322 1.74792939]]

 [[1.19979279 1.38372494 1.45644645 1.50340292 1.20487276]
  [1.95592744 1.34301452 1.47063378 1.1874014  1.82330324]
  [1.86503144 1.36822569 1.33413658 1.60327999 1.900709  ]]]


In [19]:
#12. Multiply a and c. Assign the result to e.
print('Exercise 12')
e = a*c

Exercise 12


In [20]:
#13. Does e equal to a? Why or why not?
print('Exercise 13')
print(e == a)
# All the elements are equal so both arrays are equal

Exercise 13
[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [21]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
print('Exercise 14')
d_max=np.max(d)
print(f'd_max: {d_max}')
d_min=np.min(d)
print(f'd_min: {d_min}')
d_mean=np.mean(d)
print(f'd_mean: {d_mean}')

Exercise 14
d_max: 1.9768524972975272
d_min: 1.100991037821015
d_mean: 1.4898696328853143


In [22]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
print('Exercise 15')
f = np.empty([2,3,5])
print(f)

Exercise 15
[[[1.23329397 1.9768525  1.10099104 1.3698607  1.41405295]
  [1.88659816 1.46745248 1.27761463 1.84530968 1.32235025]
  [1.3369242  1.24311748 1.7637154  1.11012322 1.74792939]]

 [[1.19979279 1.38372494 1.45644645 1.50340292 1.20487276]
  [1.95592744 1.34301452 1.47063378 1.1874014  1.82330324]
  [1.86503144 1.36822569 1.33413658 1.60327999 1.900709  ]]]


In [42]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
print('Exercise 16')
list_middle=[]                        # create an empty list to append all the results of the "unpacking"
for a in d:
    for b in a:
        for c in b:                    #unpacking all the 3D array
            if (d_min < c > d_mean):
               list_middle.append(25)
            elif (d_mean < c > d_max):
               list_middle.append(75)
            elif c == d_mean:
               list_middle.append(50)
            elif c == d_min:
               list_middle.append(0)
            elif c == d_max:
               list_middle.append(100)

print(list_middle)


Exercise 16
[25, 0, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25]
